config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	
	validates :image, presence: true
	validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
      
    else
      render action: 'new' 
    
    end
  end

  def update

      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.' 
      else
        render action: 'edit' 
      end
    
  end

  def destroy
    @pin.destroy
      redirect_to pins_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end  

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container"> 
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinteresting", root_path, class: "navbar-brand"%>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home
          <% end %>
        </li>
        <li><%= link_to about_path do%>
          <span class="glyphicon glyphicon-info-sign"></span> About
          <% end %>
        </li>
      <% if user_signed_in? %> 
        <li><%= link_to pins_path do%>
          <span class="glyphicon glyphicon-list-alt"></span> Pins
          <% end %>
        </li>
        <li><%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
        </li>
        <li><%= link_to edit_user_registration_path do%>
          <span class="glyphicon glyphicon-cog"></span> Settings
            <% end %>
        </li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <%end%>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>

	<%= yield %>
</div>


</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
<center>
<h1>The amiGo App</h1>

<br />

<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg" %>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</center>
</div>

app/views/pages/about.html.erb
<div class ="container">
<div class="jumbotron">
      <div class="container">
        <h1>What is amiGo?</h1>
        <p>amiGo is a mobile app that connects people through activities. We use geo-location to find cool people that live in your area who love to do the same things you like to do. Whether it is working out, going on a bike ride, playing basketball, or catching the game at the bar- amiGo helps connect you to cool people around your area.</p>
        <div class = "pull-right">
          <p><a class="btn btn-primary btn-lg" role="button">Login &raquo;</a></p></center>
        </div>  
        <div class = "pull-right">
        	<p><a class="btn btn-primary btn-lg" role="button">Sign Up &raquo;</a></p></center>
      </div>
  	  </div>
    </div>
</div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-6">
          <h2>Beta Testers</h2>
          <p>If you are interested in beta testing the amiGo app click below! </p>
          <p><a class="btn btn-default" href="#" role="button">Beta Test &raquo;</a></p>
        </div>
        <div class="col-md-6">
          <h2>Inquiries</h2>
          <p>Interested in learning more about amiGo? </p>
          <p><a class="btn btn-default" href="#" role="button">Click me! &raquo;</a></p>
       </div>


 <footer>
        <p>&copy; Company 2013</p>
      </footer>
    </div> <!-- /container -->

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class = "box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class ="panel-body">
        <%= pin.description %><br/>
       <strong> <%= pin.user.name if pin.user %></strong>
        <% if pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(pin) %>
        <%= link_to 'Delete', pin, method: :delete, data: {confirm: "Delete?"} %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
	<%= image_tag @pin.image.url(:medium) %>
<div class="panel-body">
	<p>
	  <strong>Description:</strong>
	  <%= @pin.description %>
	</p>
	<% if @pin.user == current_user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> 
	<% end %>
</div>